// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDDywjHjRf1-N8MDryL_TQfkvmxcg0a3U',
    appId: '1:1034081765195:web:2f023dd8a17cb78ee88ace',
    messagingSenderId: '1034081765195',
    projectId: 'acacia--dev',
    authDomain: 'acacia--dev.firebaseapp.com',
    storageBucket: 'acacia--dev.firebasestorage.app',
    measurementId: 'G-W2QDEBG25K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyDkgC57m99hrzyjAxellGpIYHhVBjYpkXU",
    appId: '1:1034081765195:android:ae696cba0335d872e88ace',
    messagingSenderId: '1034081765195',
    projectId: 'acacia--dev',
    storageBucket: 'acacia--dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKOotd7xJgIAuSOkcxXvjLa2u9Ij-0XaA',
    appId: '1:1034081765195:ios:e502f9c70a492eaae88ace',
    messagingSenderId: '1034081765195',
    projectId: 'acacia--dev',
    storageBucket: 'acacia--dev.firebasestorage.app',
    iosBundleId: 'com.acacia.app.dev',
  );
}
