// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5UvZynQ77T9Ypuf9qVdkhsXJROvIebEc',
    appId: '1:285154967207:web:433ef36b2ef525dde8a582',
    messagingSenderId: '285154967207',
    projectId: 'acacia--prod',
    authDomain: 'acacia--prod.firebaseapp.com',
    storageBucket: 'acacia--prod.firebasestorage.app',
    measurementId: 'G-PHQLLFZ7MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK7ibTxj6Tk3rJw16FnikD6QRZ_o594g4',
    appId: '1:285154967207:android:602b36595892c516e8a582',
    messagingSenderId: '285154967207',
    projectId: 'acacia--prod',
    storageBucket: 'acacia--prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeQZP4Vrmqt3wDX2N_5oVQ9n_IaiqgPY8',
    appId: '1:285154967207:ios:804d55b798d7f398e8a582',
    messagingSenderId: '285154967207',
    projectId: 'acacia--prod',
    storageBucket: 'acacia--prod.firebasestorage.app',
    iosBundleId: 'com.acacia.app',
  );

}